---
version: '3'

services:
  crafty:
    container_name: crafty_container
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    #restart: always
    environment:
      - TZ=America/Toronto
    ports:
      - "8000:8000"  # HTTP
      - "8443:8443"  # HTTPS
      - "8123:8123"  # DYNMAP
      - "19132:19132/udp"  # BEDROCK
      - "25500-25600:25500-25600"  # MC SERV PORT RANGE
    volumes:
      - E:\AI\docker_volume\crafty4\backups:/crafty/backups
      - E:\AI\docker_volume\crafty4\logs:/crafty/logs
      - E:\AI\docker_volume\crafty4\servers:/crafty/servers
      - E:\AI\docker_volume\crafty4\config:/crafty/app/config
      - E:\AI\docker_volume\crafty4\import:/crafty/import
