version: '3.8'

services:
  pufferpanel:
    container_name: pufferpanel
    image: pufferpanel/pufferpanel:latest
    ports:
      - "8080:8080"
      - "5657:5657"
    volumes:
      - ${CONFIG_VOLUME}:/etc/pufferpanel
      - ${LIB_VOLUME}:/var/lib/pufferpanel
      - ${DOCKER_SOCK}:/var/run/docker.sock
    restart: always
